// [lock-all/]
// Target
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus placerat mi vel tristique. Vestibulum magna magna, tempor eget pulvinar id, sagittis iaculis mauris. Pellentesque finibus nulla eu maximus euismod. Pellentesque finibus magna in iaculis egestas. Duis sed ultricies nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur sed ante eget pellentesque. Aliquam erat volutpat. Etiam porta enim ac tellus vestibulum, ut tristique dolor tempus.
// Sed purus nisl, ultricies ac consectetur a, iaculis ac purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi vehicula quis leo sed euismod. Phasellus pellentesque tortor ante, non pretium turpis bibendum id. Pellentesque ac nibh quam. Donec urna dui, luctus sed ultrices vitae, suscipit et odio. Nullam auctor sollicitudin rhoncus.
// Sed pellentesque neque lectus, eget aliquam metus porttitor eget. Duis nec faucibus sem. Sed volutpat bibendum sem, quis vehicula quam porttitor tincidunt. Sed placerat neque vitae sollicitudin dictum. Etiam sed justo eget magna ullamcorper auctor vel ut tellus. Integer quam lorem, accumsan non enim fringilla, vestibulum congue sapien. Proin tincidunt, velit ut viverra ultrices, augue velit cursus magna, vel ullamcorper purus elit sit amet massa. Aenean mattis est at imperdiet imperdiet. Aliquam vitae nisl sit amet nisl viverra facilisis. Etiam interdum rutrum neque, a dignissim massa vehicula at. Duis id mollis purus, sed consequat est.
// Phasellus id libero tortor. Vestibulum tortor nulla, consectetur et dictum a, sollicitudin eu urna. Vestibulum mauris arcu, venenatis ac cursus vel, lobortis eget quam. Aliquam ac arcu eleifend velit posuere gravida eget sed lorem. Vestibulum at convallis arcu. Donec rutrum a dui quis dapibus. Nulla eu feugiat dolor. Proin tincidunt purus quis sodales imperdiet. In in purus elit. Integer vitae molestie velit. Proin at turpis libero. Nam ut accumsan nunc.
// Quisque ac magna non enim cursus feugiat eu eget risus. Proin non porta massa. Nam elit diam, efficitur vel nunc at, viverra luctus augue. Cras id leo tellus. Sed id tempus nulla. Pellentesque vitae ligula urna. Donec finibus eu est sit amet elementum. In lacus ipsum, congue faucibus porta non, venenatis aliquam leo. Cras gravida mattis sapien, vel ultrices nibh accumsan non. Maecenas nisi sapien, hendrerit et vestibulum ac, aliquet et nibh.

// This file should not be replaced, since it is in the exclusion list
